### ISSUE TITLE
Ошибки при "Установить все сразу, автоматически, через виртуальную среду Vagrant"

### ISSUE THREAD

**Issue by marbug** [e-government-ua/i#1069]
Приветствую

OS: ubuntu 14.04

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux marbugh2 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ vagrant --version
Vagrant 1.8.1

$ git --version
git version 1.9.1

Virtualbox:
Version 5.0.12 r104815

Делаю всё по инструкции (см. "Установить все сразу, автоматически, через виртуальную среду Vagrant"):

https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B2%D1%81%D0%B5%D1%85-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BE%D0%B2

Получаю:

==> default: *************************************************
==> default: ***** SETTING UP nginx     **********************
==> default: dpkg-query: no packages found matching nginx
==> default: installing nginx  ...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libxslt1.1 nginx-common nginx-core
==> default: Suggested packages:
==> default:   fcgiwrap nginx-doc
==> default: The following NEW packages will be installed:
==> default:   libxslt1.1 nginx nginx-common nginx-core
==> default: 0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
==> default: Need to get 486 kB of archives.
==> default: After this operation, 1,758 kB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 i386 1.1.28-2build1 [140 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main nginx-common all 1.4.6-1ubuntu3.3 [18.1 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main nginx-core i386 1.4.6-1ubuntu3.3 [322 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main nginx all 1.4.6-1ubuntu3.3 [5,452 B]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 486 kB in 1s (347 kB/s)
==> default: Selecting previously unselected package libxslt1.1:i386.
==> default: (Reading database ... 68239 files and directories currently installed.)
==> default: Preparing to unpack .../libxslt1.1_1.1.28-2build1_i386.deb ...
==> default: Unpacking libxslt1.1:i386 (1.1.28-2build1) ...
==> default: Selecting previously unselected package nginx-common.
==> default: Preparing to unpack .../nginx-common_1.4.6-1ubuntu3.3_all.deb ...
==> default: Unpacking nginx-common (1.4.6-1ubuntu3.3) ...
==> default: Selecting previously unselected package nginx-core.
==> default: Preparing to unpack .../nginx-core_1.4.6-1ubuntu3.3_i386.deb ...
==> default: Unpacking nginx-core (1.4.6-1ubuntu3.3) ...
==> default: Selecting previously unselected package nginx.
==> default: Preparing to unpack .../nginx_1.4.6-1ubuntu3.3_all.deb ...
==> default: Unpacking nginx (1.4.6-1ubuntu3.3) ...
==> default: Processing triggers for ufw (0.34~rc-0ubuntu2) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Setting up libxslt1.1:i386 (1.1.28-2build1) ...
==> default: Setting up nginx-common (1.4.6-1ubuntu3.3) ...
==> default: Processing triggers for ufw (0.34~rc-0ubuntu2) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Setting up nginx-core (1.4.6-1ubuntu3.3) ...
==> default: Setting up nginx (1.4.6-1ubuntu3.3) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
==> default: copy dev ssl certificate/key to /etc/nginx/ssl/ folder 
==> default: Add new Vhost to local hosts file
==> default: e-gov-ua.dev added
==> default: admin.e-gov-ua.dev added
==> default: Add new Vhost(e-gov-ua.dev) to nginx
==> default: Add new Vhost(admin.e-gov-ua.dev) to nginx
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: *************************************************
==> default: e-gov-ua.dev , admin.e-gov-ua.dev now avaliable !
==> default: *************************************************
==> default: ******************************************************************
==> default: ** Finalizing setup                                             **
==> default: ******************************************************************
==> default: setting up environment
==> default: ******************************************************************
==> default: ** Provisioning complete, ready to build and deploy projects    **
==> default: ******************************************************************
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20160108-21351-tai8y3.sh
==> default: Clean up the project
==> default: [INFO] Scanning for projects...
==> default: [ERROR] [ERROR] Some problems were encountered while processing the POMs:
==> default: [WARNING] 'parent.relativePath' of POM org.egov-ua:org.egov-ua.auth-custom:1.0-SNAPSHOT (/project/auth-custom/pom.xml) points at org.igov:root instead of org.egov-ua:org.egov-ua, please verify your project structure @ line 50, column 13
==> default: [FATAL] Non-resolvable parent POM for org.egov-ua:org.egov-ua.auth-custom:1.0-SNAPSHOT: Could not find artifact org.egov-ua:org.egov-ua:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 50, column 13
==> default: [WARNING] 'version' contains an expression but should be a constant. @ org.igov:db-kv-statical:${igov.storage-static.version}, /project/storage-static/pom.xml, line 15, column 14
==> default: [WARNING] 'version' contains an expression but should be a constant. @ org.igov:db-kv-temp:${igov.storage-temp.version}, /project/storage-temp/pom.xml, line 15, column 14
==> default: [WARNING] 'version' contains an expression but should be a constant. @ org.igov:wf-base:${igov.wf-base.version}, /project/wf-base/pom.xml, line 15, column 14
==> default: [WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jar-plugin @ org.igov:wf-base:${igov.wf-base.version}, /project/wf-base/pom.xml, line 114, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.apache.tomcat.maven:tomcat7-maven-plugin is missing. @ org.igov:wf-base:${igov.wf-base.version}, /project/wf-base/pom.xml, line 102, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.zeroturnaround:jrebel-maven-plugin is missing. @ org.igov:wf-base:${igov.wf-base.version}, /project/wf-base/pom.xml, line 71, column 21
==> default: [WARNING] 'version' contains an expression but should be a constant. @ org.igov:wf-region:${igov.wf-region.version}, /project/wf-region/pom.xml, line 15, column 14
==> default: [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework:spring-test:jar -> version 4.0.6.RELEASE vs 4.1.4.RELEASE @ org.igov:wf-region:${igov.wf-region.version}, /project/wf-region/pom.xml, line 422, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.apache.tomcat.maven:tomcat7-maven-plugin is missing. @ org.igov:wf-region:${igov.wf-region.version}, /project/wf-region/pom.xml, line 68, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.zeroturnaround:jrebel-maven-plugin is missing. @ org.igov:wf-region:${igov.wf-region.version}, /project/wf-region/pom.xml, line 45, column 21
==> default: [WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
==> default: [WARNING] 'version' contains an expression but should be a constant. @ org.igov:wf-central:${igov.wf-central.version}, /project/wf-central/pom.xml, line 15, column 14
==> default: [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework:spring-test:jar -> version 4.0.6.RELEASE vs 4.1.4.RELEASE @ org.igov:wf-central:${igov.wf-central.version}, /project/wf-central/pom.xml, line 466, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.apache.tomcat.maven:tomcat7-maven-plugin is missing. @ org.igov:wf-central:${igov.wf-central.version}, /project/wf-central/pom.xml, line 69, column 21
==> default: [WARNING] 'build.plugins.plugin.version' for org.zeroturnaround:jrebel-maven-plugin is missing. @ org.igov:wf-central:${igov.wf-central.version}, /project/wf-central/pom.xml, line 46, column 21
==> default: [WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
==> default:  @ 
==> default: [ERROR] The build could not read 1 project -> [Help 1]
==> default: [ERROR]   
==> default: [ERROR]   The project org.egov-ua:org.egov-ua.auth-custom:1.0-SNAPSHOT (/project/auth-custom/pom.xml) has 1 error
==> default: [ERROR]     Non-resolvable parent POM for org.egov-ua:org.egov-ua.auth-custom:1.0-SNAPSHOT: Could not find artifact org.egov-ua:org.egov-ua:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 50, column 13 -> [Help 2]
==> default: [ERROR] 
==> default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
==> default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
==> default: [ERROR] 
==> default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
==> default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
==> default: [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by marbug** [comment]
Запуск после этого:

$ vagrant suspend
$ vagrant up

выдаёт:

==> default: Shutdown Tomcat for safer deploy
==> default: (may throw java.net.ConnectException: Connection refused if Tomcat isnt yet running - its ok, just ignore it. Will fix later.)
==> default: Jan 08, 2016 2:04:26 PM org.apache.catalina.startup.Catalina stopServer
==> default: SEVERE: Could not contact localhost:8005. Tomcat may not be running.
==> default: Jan 08, 2016 2:04:26 PM org.apache.catalina.startup.Catalina stopServer
==> default: SEVERE: Catalina.stop: 
==> default: java.net.ConnectException: Connection refused
==> default: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
==> default: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
==> default: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
==> default: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
==> default: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
==> default: 	at java.net.Socket.connect(Socket.java:579)
==> default: 	at java.net.Socket.connect(Socket.java:528)
==> default: 	at java.net.Socket.<init>(Socket.java:425)
==> default: 	at java.net.Socket.<init>(Socket.java:208)
==> default: 	at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:450)
==> default: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
==> default: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
==> default: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
==> default: 	at java.lang.reflect.Method.invoke(Method.java:606)
==> default: 	at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:400)
==> default: 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:487)
==> default: Copy WAR to webapps dir
==> default: cp: 
==> default: cannot stat ‘/project/wf-region/target/wf-region.war’
==> default: : No such file or directory
==> default: Start Tomcat
==> default: Tomcat started.
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20160108-25727-nui4l4.sh
==> default: starting central-js
==> default: npm install ...

Т.е. вроде бы проигнорило - пошло дальше.
Может стОит это как-то пофиксить?

P.S. Аналогично матюкалось на отсутствие nfsd. Пофиксил:
$ sudo apt-get install nfs-kernel-server

**Comment by marbug** [comment]
Или может есть смысл добавить информацию в "Что если ..."
https://github.com/e-government-ua/i/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B2%D1%81%D0%B5%D1%85-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BE%D0%B2#%D0%A7%D1%82%D0%BE-%D0%B5%D1%81%D0%BB%D0%B8
?

**Comment by marbug** [comment]
==> default: starting central-js
==> default: npm install ...
==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  lodash@1.3.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  CSSselect@0.7.0: the module is now available as 'css-select'
==> default: npm
==> default:  
==> default: WARN
==> default:  
==> default: deprecated
==> default:  CSSwhat@0.4.7: the module is now available as 'css-what'

**Comment by marbug** [comment]
Т.к. вылазят ошибки вида

==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-dialog-service failed with ETIMEDOUT, retrying in 1.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-i18n failed with ETIMEDOUT, retrying in 1.1s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-jsoneditor failed with ETIMEDOUT, retrying in 1.2s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-messages failed with ETIMEDOUT, retrying in 1.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui failed with ETIMEDOUT, retrying in 1.2s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui-event failed with ETIMEDOUT, retrying in 1.3s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui-router failed with ETIMEDOUT, retrying in 1.9s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui-uploader failed with ETIMEDOUT, retrying in 1.3s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/bootstrap-sass-official failed with ETIMEDOUT, retrying in 1.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/intl-tel-input failed with ETIMEDOUT, retrying in 1.9s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/jquery.cookie failed with ETIMEDOUT, retrying in 2.0s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/jsoneditor failed with ETIMEDOUT, retrying in 1.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/textAngular failed with ETIMEDOUT, retrying in 1.6s
==> default: bower angular-bootstrap#~0.12.1            retry Download of https://github.com/angular-ui/bootstrap-bower/archive/0.12.1.tar.gz failed with ESOCKETTIMEDOUT, retrying in 1.8s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-i18n failed with ETIMEDOUT, retrying in 2.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-jsoneditor failed with ETIMEDOUT, retrying in 2.0s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/jquery.cookie failed with ESOCKETTIMEDOUT, retrying in 3.0s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui failed with ETIMEDOUT, retrying in 2.7s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/jsoneditor failed with ETIMEDOUT, retrying in 3.7s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/bootstrap-sass-official failed with ETIMEDOUT, retrying in 2.5s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-dialog-service failed with ETIMEDOUT, retrying in 3.3s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/textAngular failed with ETIMEDOUT, retrying in 2.2s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/angular-ui-router failed with ETIMEDOUT, retrying in 2.6s
==> default: bower                                      retry Request to https://bower.herokuapp.com/packages/intl-tel-input failed with ETIMEDOUT, retrying in 2.1s
==> default: bower angular#1.3.15                    download https://github.com/angular/bower-angular/archive/v1.3.15.tar.gz
==> default: bower bootstrap#~3.3.5                  download https://github.com/twbs/bootstrap/archive/v3.3.6.tar.gz
==> default: bower angular-ui-event#~1.0.0          ENOTFOUND Request to https://bower.herokuapp.com/packages/angular-ui-event failed: getaddrinfo ENOTFOUND bower.herokuapp.com
==> default: run grunt serve in screen, to restore type 'screen -r central-js'

вделал:

$ vagrant ssh
$ cd /project/central-js
$ npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

$ bower update

Please note that,
    angular-bootstrap#0.12.1 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.29
    central-js depends on angular#1.3.15 which resolved to angular#1.3.15
    angular-cookies#1.4.8, angular-messages#1.4.8, angular-mocks#1.4.8, angular-resource#1.4.8, angular-sanitize#1.4.8, angular-scenario#1.4.8 depends on angular#1.4.8 which resolved to angular#1.4.8
    angular-ui-event#1.0.0, angular-ui-uploader#1.1.3 depends on angular#>= 1.0.5 which resolved to angular#1.4.8
    angular-jsoneditor#7c3af39620 depends on angular#>=1.0.6 which resolved to angular#1.4.8
    angular-dialog-service#5.2.11 depends on angular#^1.3 which resolved to angular#1.4.8
    angular-moment#0.10.3 depends on angular#>=1.2.0 <1.5.0 which resolved to angular#1.4.8
    textAngular#1.4.6 depends on angular#>=1.3.x which resolved to angular#1.4.8
    angular-bootstrap#0.14.3 depends on angular#>=1.3.0 which resolved to angular#1.4.8
    angular-ui-router#0.2.15 depends on angular#>= 1.0.8 which resolved to angular#1.4.8
    angular-translate#2.8.1 depends on angular#>=1.2.26 <=1.5 which resolved to angular#1.4.8
    ng-clip#0.2.6 depends on angular#>=1.0.4 which resolved to angular#1.4.8
Resort to using angular#1.3.15 which resolved to angular#1.3.15
Code incompatibilities may occur.


Unable to find a suitable version for angular-bootstrap, please choose one:
    1) angular-bootstrap#~0.12.1 which resolved to 0.12.1 and is required by central-js
    2) angular-bootstrap#^0.14.3 which resolved to 0.14.3 and is required by angular-dialog-service#5.2.11

Prefix the choice with ! to persist it to bower.json

? Answer 2 <--------------------- я выбрал 2

Please note that,
    angular-jsoneditor#7c3af39620 depends on jsoneditor#~3.1.2 which resolved to jsoneditor#3.1.2
    central-js depends on jsoneditor#~4.2.1 which resolved to jsoneditor#4.2.1
Resort to using jsoneditor#~4.2.1 which resolved to jsoneditor#4.2.1
Code incompatibilities may occur.

... (аля "всё ок")

$ cd /project/central-js
$ npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

$ bower update

... (аля "всё ок")

$ exit
$ vagrant suspend
$ vagrant up

теперь открыло
http://192.168.10.10:9000/
но с ошибкой на вебе

ПОМИЛКА [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: category in catalog, Duplicate key: string:<, Duplicate value: < http://errors.angularjs.org/1.3.15/ngRepeat/dupes?p0=category%20in%20catalog&p1=string%3A%3C&p2=%3C (caused by "undefined")

**Comment by marbug** [comment]
Предлагаю:
1) определиться с версиями используемого софта (на фронтенде)
2) пофиксить все зависимости
3) решить проблемы для нормальной установки с помощью Vagrant-а
