### ISSUE TITLE
Ошибка в разделе Документы, если у пользователя еще нет документов

### ISSUE THREAD

**Issue by lem8r** [e-government-ua/i#1302]
На боевом сервере при переходе в раздел Документы от имени пользователя, у которого еще нет документов вылазит ошибка.
![2016-07-08 13-27-12](https://cloud.githubusercontent.com/assets/5942291/16684911/45deac1a-4510-11e6-877d-08622fc76046.png)

В консоли на локальном фронт-енде лог примерно такой:
```
GET /app/documents/index.html 200 5ms
GET /auth/isAuthenticated 200 1ms
GET /auth/isAuthenticated 200 1ms
GET /app/documents/user/index.html 200 3ms - 261b
GET /api/user/fio 304 1ms
GET /api/user/fio 304 1ms
GET /%7B%7Bads.image%7D%7D 304 13ms
GET /%7B%7Bads.image%7D%7D 304 13ms
GET /auth/isAuthenticated 200 12ms
GET /auth/isAuthenticated 200 12ms
REQUEST { url: 'https://test.igov.org.ua/wf/service/document/getDocuments',
  auth: { username: 'activiti-master', password: 'UjhtJnEvf!' },
  qs: { nID_Subject: 79367 },
  callback: [Function] }
REQUEST { url: 'https://test.igov.org.ua/wf/service/document/getDocumentTypes',
  auth: { username: 'activiti-master', password: 'UjhtJnEvf!' },
  qs: { nID_Subject: 79367 },
  callback: [Function] }
REQUEST make request https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367
REQUEST make request https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367
REQUEST onRequestResponse https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367 200 { server: 'nginx/1.9.5',
  date: 'Fri, 08 Jul 2016 10:08:06 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '2',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367
REQUEST response end https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367 200 { server: 'nginx/1.9.5',
  date: 'Fri, 08 Jul 2016 10:08:06 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '2',
  connection: 'close' }
REQUEST end event https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367
REQUEST has body https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367 2
REQUEST emitting complete https://test.igov.org.ua/wf/service/document/getDocuments?nID_Subject=79367
GET /api/documents 200 332ms - 2b
GET /api/documents 200 332ms - 2b
REQUEST onRequestResponse https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367 200 { server: 'nginx/1.9.5',
  date: 'Fri, 08 Jul 2016 10:08:06 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '464',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367
REQUEST response end https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367 200 { server: 'nginx/1.9.5',
  date: 'Fri, 08 Jul 2016 10:08:06 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '464',
  connection: 'close' }
REQUEST end event https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367
REQUEST has body https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367 464
REQUEST emitting complete https://test.igov.org.ua/wf/service/document/getDocumentTypes?nID_Subject=79367
GET /api/documents/search/getDocumentTypes 200 336ms - 464b
GET /api/documents/search/getDocumentTypes 200 336ms - 464b
REQUEST { url: 'https://bankid.privatbank.ua/ResourceService/checked/data',
  headers: 
   { 'Content-Type': 'application/json',
     Authorization: 'Bearer 39fb4dd0-8feb-4daa-a79b-353da8c03896, Id testIgov',
     Accept: 'application/json' },
  json: true,
  body: 
   { type: 'physical',
     fields: 
      [ 'firstName',
        'middleName',
        'lastName',
        'phone',
        'inn',
        'clId',
        'clIdText',
        'birthDay' ],
     scans: [ [Object], [Object] ] },
  callback: [Function],
  method: 'POST' }
REQUEST make request https://bankid.privatbank.ua/ResourceService/checked/data
REQUEST onRequestResponse https://bankid.privatbank.ua/ResourceService/checked/data 200 { server: 'nginx',
  date: 'Fri, 08 Jul 2016 10:08:08 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '588',
  connection: 'close',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
  pragma: 'no-cache',
  expires: '0',
  'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Authorization, content-type',
  'access-control-allow-methods': 'GET, OPTIONS, POST',
  'access-control-allow-credentials': 'true' }
REQUEST reading response's body
REQUEST finish init function https://bankid.privatbank.ua/ResourceService/checked/data
REQUEST response end https://bankid.privatbank.ua/ResourceService/checked/data 200 { server: 'nginx',
  date: 'Fri, 08 Jul 2016 10:08:08 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '588',
  connection: 'close',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
  pragma: 'no-cache',
  expires: '0',
  'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Authorization, content-type',
  'access-control-allow-methods': 'GET, OPTIONS, POST',
  'access-control-allow-credentials': 'true' }
REQUEST end event https://bankid.privatbank.ua/ResourceService/checked/data
REQUEST has body https://bankid.privatbank.ua/ResourceService/checked/data 588
REQUEST emitting complete https://bankid.privatbank.ua/ResourceService/checked/data
/home/lem8r/bin/iGov/i/central-js/server/api/documents/documents.controller.js:185
    bankIDService.scanContentRequest(documentScan.scan.type, documentScan.scan.link, accessToken, function (error, buffer) {
                                                      ^

TypeError: Cannot read property 'type' of undefined
    at uploadScan (/home/lem8r/bin/iGov/i/central-js/server/api/documents/documents.controller.js:185:55)
    at async.forEach.req.session.documents.uploaded (/home/lem8r/bin/iGov/i/central-js/server/api/documents/documents.controller.js:222:9)
    at /home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:162:20
    at /home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:230:13
    at _arrayEach (/home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:81:9)
    at _each (/home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/home/lem8r/bin/iGov/i/central-js/node_modules/async/lib/async.js:206:22)
    at doAsyncScansUpload (/home/lem8r/bin/iGov/i/central-js/server/api/documents/documents.controller.js:219:11)
    at scansCallback (/home/lem8r/bin/iGov/i/central-js/server/api/documents/documents.controller.js:244:11)
```

**Comment by lem8r** [comment]
Для теста нужно зайти в раздел /documents от имени пользователя у которого еще нет документов
