### ISSUE TITLE
Пользователь центрального портала должен иметь возможность авторизоваться с помощью BankID-НБУ

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#1328]

**Comment by AleksejDomash** [comment]
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
   at fromObject (buffer.js:287:9)
   at Function.Buffer.from (buffer.js:133:10)
   at new Buffer (buffer.js:112:17)
   at /usr/src/app/server/auth/bankid-nbu/index.js:25:16
   at NBUOAuth2Strategy.strategy.error (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:333:18)
   at NBUOAuth2Strategy.OAuth2Strategy.authenticate (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:126:19)
   at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at /usr/src/app/server/auth/bankid-nbu/index.js:46:5
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)`
".... т.е. я подключился к ПУМБу ввёл свои данные, мне пришла смс с кодом, я ввёл код из смс в формочку и потом эта ошибка.... "

**Comment by AleksejDomash** [comment]
добавил фикс по ошибке выше

**Comment by AleksejDomash** [comment]
нет возможности тестировать локально из-за отсутствия карты ощадбанка-пумба. Тестового логина эти банки не предоставили на данный момент

**Comment by AleksejDomash** [comment]
последние ошибки из логов
`central-js-0 [90mGET /auth/bankid-nbu/callback?error=server_error&error_description=server_error&code=503 `

**Comment by AleksejDomash** [comment]
ОЩАДБАНК без шифрования - работает

**Comment by AleksejDomash** [comment]
ПУМБ - ошибки на стороне самого банка

**Comment by AleksejDomash** [comment]
По шифрованию идет дискуссия. RSA не может подписывать большие JSON объекты, как это написано в документации
