### ISSUE TITLE
Process bankid result in a userfriendly way

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#1407]
2016-10-19_15:25:33.129: Error: can't decrypt value undefined field undefined because of
must start with number, buffer, array or string
    at decryptValue (/sybase/central-js/server/auth/bankid/bankid.util.js:138:11)
    at Object.module.exports.decryptField (/sybase/central-js/server/auth/bankid/bankid.util.js:102:12)
    at adminCheckCallback (/sybase/central-js/server/auth/bankid/bankid.service.js:64:31)
    at Request._callback (/sybase/central-js/server/auth/bankid/bankid.service.js:49:9)
    at Request.self.callback (/sybase/central-js/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/sybase/central-js/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/sybase/central-js/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:129:20)

**Comment by AleksejDomash** [comment]
2016-10-19_11:03:53.094: TypeError: Cannot read property 'inn' of undefined
    at adminCheckCallback (/sybase/central-js/server/auth/bankid/bankid.service.js:63:87)
    at Request._callback (/sybase/central-js/server/auth/bankid/bankid.service.js:49:9)
    at Request.self.callback (/sybase/central-js/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/sybase/central-js/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/sybase/central-js/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:907:16
    at process._tickDomainCallback (node.js:403:11)

**Comment by AleksejDomash** [comment]
2016-10-19_16:15:42.501: [90mGET /api/process-form?nID_Server=0&sID_BP_Versioned=dnepr_mvk_291_common:81:68117564 [36m304 [90m64ms[0m
2016-10-19_16:15:42.545: --------------- enter admin callback !!!!
2016-10-19_16:15:42.545: ---------------  innToCheck before decryption !!!!undefined
