### ISSUE TITLE
SyntaxError: Invalid regular expression api/places/index.controller

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#1408]
2016-10-18_14:59:34.335: SyntaxError: Invalid regular expression: /Подільськ (Котовськ/: Unterminated group
    at new RegExp (native)
    at Object.findCities [as getCities] (/sybase/central-js/server/api/places/index.controller.js:90:29)
    at /sybase/central-js/server/api/places/index.js:69:21
    at Layer.handle [as handle_request] (/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at next (/sybase/central-js/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/sybase/central-js/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at /sybase/central-js/node_modules/express/lib/router/index.js:277:22
    at param (/sybase/central-js/node_modules/express/lib/router/index.js:349:14)
    at param (/sybase/central-js/node_modules/express/lib/router/index.js:365:14)

**Comment by AleksejDomash** [comment]
2016-10-18_17:20:44.487: SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at Object.findRegions [as getRegions] (/sybase/central-js/server/api/places/index.controller.js:23:29)
    at /sybase/central-js/server/api/places/index.js:51:23
    at Layer.handle [as handle_request] (/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at next (/sybase/central-js/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/sybase/central-js/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at /sybase/central-js/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/sybase/central-js/node_modules/express/lib/router/index.js:330:12)
    at next (/sybase/central-js/node_modules/express/lib/router/index.js:271:10)

**Comment by donvadicastro** [comment]
А можно получить еще какой-то хотя бы поверхностый StepToReproduce для этих багов?
