### ISSUE TITLE
TypeError: Cannot read property 'formProperties' of undefined api/process-form/form.controller.js

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#1409]
2016-10-18_17:42:45.301: TypeError: Cannot read property 'formProperties' of undefined
    at createHtml (/sybase/central-js/server/api/process-form/form.controller.js:574:42)
    at /sybase/central-js/server/api/process-form/form.controller.js:625:9
    at fn (/sybase/central-js/node_modules/async/lib/async.js:712:34)
    at /sybase/central-js/node_modules/async/lib/async.js:1165:16
    at /sybase/central-js/node_modules/async/lib/async.js:657:43
    at /sybase/central-js/node_modules/async/lib/async.js:1161:30
    at Request._callback (/sybase/central-js/server/api/process-form/form.controller.js:619:13)
    at Request.self.callback (/sybase/central-js/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/sybase/central-js/node_modules/request/request.js:1048:10)

**Comment by GFalcon-UA** [comment]
эту ошибку кажется один раз встречал, когда форма заявки прогружается после прохождения авторизации в БанкИД, а АктивитиСервис форму еще не отдало...
