### ISSUE TITLE
TypeError: Cannot read property 'nID' of undefined api/messages/index.controller

### ISSUE THREAD

**Issue by AleksejDomash** [e-government-ua/i#1411]
2016-10-18_23:48:32.376: TypeError: Cannot read property 'nID' of undefined
    at module.exports.postServiceMessage (/sybase/central-js/server/api/messages/index.controller.js:138:28)
    at Layer.handle [as handle_request](/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at next (/sybase/central-js/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/sybase/central-js/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/sybase/central-js/node_modules/express/lib/router/layer.js:95:5)
    at /sybase/central-js/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/sybase/central-js/node_modules/express/lib/router/index.js:330:12)
    at next (/sybase/central-js/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/sybase/central-js/node_modules/express/lib/router/index.js:176:3)
    at router (/sybase/central-js/node_modules/express/lib/router/index.js:46:12)

**Comment by donvadicastro** [comment]
Could you please provide at least high-level StepToReproduce for this bug? Thanks in advance.
