### ISSUE TITLE
Реализовать отдельный сервис getDocumentAbstract, на основе getDocumentFile

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#729]
Пока просто скопировать его с getDocumentFile и:
1) убрать поле nID
2) заменить поле sCode_DocumentAccess на sID
3) Оптимизировать структуру с учетом изменений п.1 и п.2
4) Дописать документацию АПИ на Вики

**Comment by nazarenkod** [comment]
Как можно проверить?

**Comment by VadimGulich** [comment]
Прошу дать описание как можно протестировать или ссылку на АПИ в вики

**Comment by taaraora** [comment]
В этом разделе - https://github.com/e-government-ua/i/blob/test/docs/specification.md#9-Работа-с-документами
немного ниже есть описание. Можно просто поиском по стрианце поискать  по фразе "getDocumentAbstract"

**Comment by nazarenkod** [comment]
Запрос 
https://test.igov.org.ua/wf/service/services/getDocumentAbstract?sID=150826SV7733A36E803B
вернул 
{
code: "SYSTEM_ERR"
message: "Specify value"
}

я где то ошибся?

**Comment by OlgaTurenko** [comment]
2015-11-22_16:05:49.178 | ERROR | org.activiti.rest.controller.ActivitiExceptionController- REST System Exception: Specify value
java.lang.IllegalArgumentException: Specify value
        at org.springframework.util.Assert.notNull(Assert.java:112)
        at org.wf.dp.dniprorada.base.dao.GenericEntityDao.findByAttributeCriteria(GenericEntityDao.java:109)
        at org.wf.dp.dniprorada.base.dao.GenericEntityDao.findBy(GenericEntityDao.java:84)
        at org.wf.dp.dniprorada.base.dao.GenericEntityDao.findByExpected(GenericEntityDao.java:93)
        at org.wf.dp.dniprorada.base.dao.GenericEntityDao$$FastClassBySpringCGLIB$$7940f40a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
        at org.wf.dp.dniprorada.base.dao.GenericEntityDao$$EnhancerBySpringCGLIB$$73f4e677.findByExpected(<generated>)
        at org.wf.dp.dniprorada.dao.DocumentDaoImpl.getOperator(DocumentDaoImpl.java:98)

Просьба посмотреть.
